version: "3.6"
services:
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=audiophile
      - POSTGRES_PORT=5432
  server:
      image: audio-3:latest
      ports:
        - '8080:8080'
      links:
        - db
      environment:
        - host=db
      depends_on:
        - db